using System;
using System.Collections.Generic;
using System.Linq;
using DeepEyeUnlocker.Core.Models;
using DeepEyeUnlocker.Infrastructure.HIL;

namespace DeepEyeUnlocker.Core.AI
{
    public class ScenarioSynthesizer
    {
        public ProtocolScenario GenerateScenario(LlmAnalysis analysis, List<UsbPacket> originalPackets)
        {
            var scenario = new ProtocolScenario
            {
                Name = $"auto_{analysis.ProtocolType}_{DateTime.Now:yyyyMMdd_HHmm}",
                Description = $"Auto-generated by PAA: {analysis.Summary}",
            };

            var steps = new List<ScenarioStep>();
            for (int i = 0; i < Math.Min(analysis.Steps.Count, originalPackets.Count); i++)
            {
                var inferredStep = analysis.Steps[i];
                var packet = originalPackets[i];

                steps.Add(new ScenarioStep
                {
                    Label = inferredStep.Description,
                    Direction = MapDirection(inferredStep.Direction),
                    DataHex = SanitizeData(packet.Data),
                    DelayMs = i > 0 ? (int)((packet.TimestampUs - originalPackets[i-1].TimestampUs) / 1000) : 0
                });
            }

            scenario.Steps = steps;
            return scenario;
        }

        private StepDirection MapDirection(string dir)
        {
            var cleanDir = dir.ToLower();
            if (cleanDir.StartsWith("host") || cleanDir.Contains("to_device") || cleanDir.Contains("code_out")) 
                return StepDirection.HostToDevice;
                
            return StepDirection.DeviceToHost;
        }

        private string SanitizeData(byte[] data)
        {
            // Placeholder for data sanitization (e.g., redacting IDs)
            return BitConverter.ToString(data).Replace("-", "");
        }
    }
}
