package com.deepeye.otg.ui.screens

enum class NavTarget {
    HOME,
    DEVICES,
    SETTINGS,
    IMEI_REPAIR,
    DASHBOARD,
    FILE_EXPLORER,
    IPHONE_15_RESEARCH,
    TERMINAL,
    VAULT,
    STORAGE,
    PARTITION_EXPLORER,
    CVE_INTELLIGENCE,
    FUZZ_DASHBOARD,
    HID_RESEARCH,
    FORENSICS_LAB,
    DEVICE_SUPPORT
}
