import json
import os
import sys

def generate_ghidra_script(signatures_file, output_script):
    with open(signatures_file, 'r') as f:
        data = json.load(f)
        
    script_content = "# Autogenerated Ghidra script for SEPOS RE\n"
    script_content += "from ghidra.program.model.symbol import SourceType\n\n"
    
    for chip, details in data.items():
        script_content += f"# --- {chip} ---\n"
        for func in details['functions']:
            script_content += f"createLabel(toAddr({func['offset']}), '{func['name']}', True, SourceType.USER_DEFINED)\n"
            
    with open(output_script, 'w') as f:
        f.write(script_content)
    print(f"Ghidra script generated: {output_script}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python generate_ghidra_project.py <signatures.json> <output.py>")
        sys.exit(1)
    generate_ghidra_script(sys.argv[1], sys.argv[2])
