// <auto-generated />
using System;
using DeepEyeUnlocker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeepEyeUnlocker.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    partial class DeviceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DeepEyeUnlocker.Core.Models.DeviceProfile", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InterfaceClassGuids")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedBootModes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DeepEyeUnlocker.Core.Models.DeviceProfile", b =>
                {
                    b.OwnsOne("DeepEyeUnlocker.Core.Models.ChipsetInfo", "Chipset", b1 =>
                        {
                            b1.Property<string>("DeviceProfileProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Architecture")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Manufacturer")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("SupportedUniversalMethods")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("DeviceProfileProfileId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceProfileProfileId");
                        });

                    b.OwnsMany("DeepEyeUnlocker.Core.Models.FirmwareInfo", "KnownFirmwares", b1 =>
                        {
                            b1.Property<string>("DeviceProfileProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AndroidVersion")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReleaseDate")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("DeviceProfileProfileId", "Id");

                            b1.ToTable("Devices");

                            b1.ToJson("KnownFirmwares");

                            b1.WithOwner()
                                .HasForeignKey("DeviceProfileProfileId");
                        });

                    b.OwnsMany("DeepEyeUnlocker.Core.Models.OperationSupport", "SupportedOperations", b1 =>
                        {
                            b1.Property<string>("DeviceProfileProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("HandlerName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("LastVerified")
                                .HasColumnType("TEXT");

                            b1.Property<string>("OperationName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Prerequisites")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProtocolPlugin")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("RequiresAuth")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("RiskLevel")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeviceProfileProfileId", "Id");

                            b1.ToTable("Devices");

                            b1.ToJson("SupportedOperations");

                            b1.WithOwner()
                                .HasForeignKey("DeviceProfileProfileId");
                        });

                    b.OwnsOne("DeepEyeUnlocker.Core.Models.SecurityProfile", "Security", b1 =>
                        {
                            b1.Property<string>("DeviceProfileProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("EncryptedUserData")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PatchLevel")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("SecureBoot")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeviceProfileProfileId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceProfileProfileId");
                        });

                    b.OwnsMany("DeepEyeUnlocker.Core.Models.UsbIdentifier", "UsbIds", b1 =>
                        {
                            b1.Property<string>("DeviceProfileProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Pid")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Vid")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DeviceProfileProfileId", "Id");

                            b1.ToTable("Devices");

                            b1.ToJson("UsbIds");

                            b1.WithOwner()
                                .HasForeignKey("DeviceProfileProfileId");
                        });

                    b.Navigation("Chipset")
                        .IsRequired();

                    b.Navigation("KnownFirmwares");

                    b.Navigation("Security")
                        .IsRequired();

                    b.Navigation("SupportedOperations");

                    b.Navigation("UsbIds");
                });
#pragma warning restore 612, 618
        }
    }
}
